
export enum EVariant {
  DEFAULT, CREDENTIALLIST, LOGINLIST
  , PILOTDETAILS, PILOTROASTER, PILOTINFORMATION
  , PILOTMANAGERS, ASSETSMANAGER, PLANETARYMANAGER, PLANETARYOPTIMIZATION
  , FITTING_MANAGER, FITTINGLIST, FITTING_ACTIONS_BYCLASS
  , ASSETS_BY_LOCATION
}
