
export enum EVariant {
  DEFAULT, CREDENTIALLIST, LOGINLIST, PILOTDETAILS, PILOTROASTER, PILOTMANAGERS, ASSETSMANAGER, PLANETARYMANAGER, PLANETARYOPTIMIZATION,
  FITTINGLIST, FITTING_ACTIONS_BYCLASS
}
